a=int(input("Digite o primeiro número: ")) 
b=int(input("Digite o segundo número: "))
print("O Resultado da sua soma é:", a+b) 
print("O Resultado da sua subtração é:", a-b)
print("O Resultado da sua multiplicação é:", a*b)
print("O Resultado da sua divisão é:", a/b)